---
output_dir: ../kubernetes-manifests-infra/jenkins

namespace: jenkins

image: harbor.freedom.org/freedom/jenkins-centos7:2.319.1-1.1

jenkins_exporter_image: harbor.freedom.org/bitnami/jenkins-exporter:latest

storageclass: storageclass-nfs-infra

storageclass_capacity: 50G