apiVersion: v1
kind: Secret
metadata:
  labels:
    alertmanager: main
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.21.0
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    "global":
      "resolve_timeout": "5m"

    "route":
      "receiver": "Default"
      "group_by":
        - "namespace"
      "group_interval": "5m"
      "group_wait": "30s"
      "repeat_interval": "10m"
      "routes":
        - "match":
            "alertname": "Watchdog"
          "receiver": "Watchdog"

    "receivers":
      - "name": "Watchdog"
      - "name": "Default"
        "webhook_configs":
          - "url": "http://qywx-robots.devops:8080/default"

    "inhibit_rules":
      - "equal":
          - "namespace"
          - "alertname"
        "source_match":
          "severity": "critical"
        "target_match_re":
          "severity": "warning|info"
      - "equal":
          - "namespace"
          - "alertname"
        "source_match":
          "severity": "warning"
        "target_match_re":
          "severity": "info"
type: Opaque
