---
apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-agent
  namespace: consul
data:
  agent.json: |
    {
      "services": [
          {
              "name": "consul-agent",
              "port": 8500,
              "tags": [
                  "consul-agent"
              ]
          },
          {
              "name": "k8s-node-exporter",
              "port": 9100,
              "tags": [
                  "k8s-node-exporter"
              ]
          }
      ]
    }