apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: consul-agent
  namespace: consul
  labels:
    app: consul-agent
spec:
  selector:
    matchLabels:
      app: consul-agent
  template:
    metadata:
      name: consul-agent
      labels:
        app: consul-agent
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: consul-agent
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: NODEIP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: harbor.freedom.org/docker.io/consul:1.10.2
          args:
            - "agent"
            - "-retry-join=node01.consul.freedom.org"
            - "-retry-join=node02.consul.freedom.org"
            - "-retry-join=node03.consul.freedom.org"
            - "-config-dir=/consul/config"
            - "-log-level=info"
            - "-log-rotate-duration=86400s"
            - "-log-rotate-max-files=7"
            - "-bind=0.0.0.0"
            - "-client=0.0.0.0"
            - "-advertise=$(NODEIP)"
            - "-domain=k8s.freedom.org"
            - "-disable-host-node-id"
            - "-datacenter=default"
            - "-node=$(NODENAME)"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8500
            - name: serflan-tcp
              containerPort: 8301
            - name: consuldns
              containerPort: 8600
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
          readinessProbe:
            httpGet:
              port: http
              path: /
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 60
          livenessProbe:
            httpGet:
              port: http
              path: /
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /consul/config/agent.json
              subPath: agent.json
      volumes:
        - name: config
          configMap:
            name: consul-agent

