---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: loki
data:
  config.yaml: |
    auth_enabled: false

    server:
      http_listen_address: "0.0.0.0"
      http_listen_port: 3100
      grpc_listen_port: 9096

    ingester:
      wal:
        enabled: true
        dir: /data
      lifecycler:
        address: 0.0.0.0
        ring:
          kvstore:
            store: inmemory
          replciation_factor: 1
        final_sleep: 0s
        chunk_idle_period: 1h         # Any chunk not receiving new logs in this time will be flushed
        max_chunk_age: 1h             # All chunks will be flushed when they hit this age, default is 1h
        chunk_target_size: 1048576    # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first
        chunk_retain_period: 30s      # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
        max_transfer_retries: 0       # Chunk transfers disabled

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /data
        cache_location: /data
        cache_ttl: 24h
        shared_store: filesystem
      filesystem:
        directory: /data

    compactor:
      working_directory: /data
      shared_store: filesystem

    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 168h

    chunk_sotre_config:
      max_look_back_period: 0s

    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s

    ruler:
      storage:
        type: local
        local:
          directory: /data
      rule_path: /data
      alertmager_url: http://localhost:9093
      ring:
        kvstore:
          store: inmemory
      enable_api: true

    distributor:
      store: memberlist
      prefix: "collectors/"
      heartbeat_timeout: 1m
