---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: loki
data:
  config.yaml: |
    auth_enabled: false

    server:
      http_listen_address: "0.0.0.0"
      http_listen_port: 3100

    distributor:
      store: memberlist
      prefix: "collectors/"
      heartbeat_timeout: 1m